Added Bank Removing
EcoToolBox/AccountInterface pull request #5
Opened 2024-01-11 23:22 UTC by loudnessofthelambs

Added ability to delete a bank account for the AbstractPlayerAccount class

2024-01-11 23:35 UTC, mosemister commented on src/main/java/org/kaiaccount/account/inter/type/player/AbstractPlayerAccount.java
> +	public boolean deleteBankAccount(@NotNull String name) {
Could we have a interface method for this please?
https://github.com/EconToolBox/AccountInterface/blob/main/src/main/java/org/kaiaccount/account/inter/type/named/bank/BankAccount.java

2024-01-11 23:39 UTC, mosemister requested changes
Overall good start, just 2 minor changes

2024-01-11 23:39 UTC, mosemister commented on src/main/java/org/kaiaccount/account/inter/type/player/AbstractPlayerAccount.java
> +			return false;
The ``tab`` space seems a bit too large. If your using intellijj then you should be able to click the format button to fix this. 

I personally have ``Format, optimise imports and save`` all on the save key. You can do that with Macros. The example in the Macro setup guide is ``Format and save`` so should give you a good idea if you choose to use it

https://www.jetbrains.com/help/idea/using-macros-in-the-editor.html#reformat_on_save

2024-01-11 23:53 UTC, mosemister requested changes
Just a extremely minor change

2024-01-11 23:53 UTC, mosemister commented on src/main/java/org/kaiaccount/account/inter/type/player/AbstractPlayerAccount.java
> +    public @NotNull boolean deleteBankAccount(@NotNull String name) {
Mind just annotating this with a ``@Override`` to just make it clear its coming from a method outside the class and that the class is modifying the behaviour

2024-01-11 23:56 UTC, mosemister approved these changes, later dismissed
Approved

2024-01-22 16:37 UTC, loudnessofthelambs commented
I rewrote this to work with a PlayerBankAccount instead of a name, can this be reapproved

2024-01-23 09:06 UTC, mosemister requested changes

2024-01-23 09:06 UTC, mosemister commented on src/main/java/org/kaiaccount/account/inter/type/player/PlayerAccount.java
> +	boolean deleteBankAccount(@NotNull PlayerBankAccount account);
Extra indent -> recommend using Intellij auto format

2024-04-12 18:27 UTC, mosemister commented
Due to the lack of process. I am taking over the task, I have copied the branch with #6

2024-04-12 18:27 UTC, closed without merging